[package]
name = "screenshotr"
authors = ["Erlangga Yudi Pradana"]
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = 3
codegen-units = 1

[dependencies]
axum = "0.8.8"
base64 = "0.22.1"
bcrypt = "0.18.0"
blake3 = "1.8.5"
chrono = { version = "0.4.44", features = ["serde"] }
fantoccini = "0.22.1"
getrandom = "0.4.2"
hex = "0.4.3"
hmac = "0.12.1"
log = "0.4.29"
log4rs = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
sha2 = "0.10.9"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "signal"] }
tower-http = { version = "0.6.8", features = ["fs"] }
url = "2.5.8"
uuid = { version = "1.20.0", features = ["v4"] }
